BigonWebShoppingApp/Models/Category.cs
using BigonWebShoppingApp.Models.Common;

namespace BigonWebShoppingApp.Models
{
    public class Category:BaseEntity
    {
        public string Name { get; set; }

        public Category? ParentCategory { get; set; }
        public Guid? ParentCategoryId { get; set; }
    }
}

BigonWebShoppingApp/Areas/Admin/Controllers/CategoryController.cs
using BigonWebShoppingApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.Packaging.Signing;
using System.Diagnostics.CodeAnalysis;

namespace BigonWebShoppingApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly AppDbContext _context;

        public CategoryController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var categories = _context.Categories.ToList();
            return View(categories);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories = _context.Categories.ToList();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Category category)
        {
            var parent = await _context.Categories.FirstOrDefaultAsync(x => x.Id == category.ParentCategoryId);
            category.ParentCategory = parent;
            await _context.Categories.AddAsync(category);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            var category = _context.Categories.FirstOrDefault(x => x.Id == id);
            if (category is null)
                return NotFound();
            ViewBag.Categories = _context.Categories.ToList();
            return View(category);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Category category)
        {
            var dbCate = await _context.Categories.FirstOrDefaultAsync(x => x.Id == category.Id);
            if (dbCate == null)
                return NotFound();

            dbCate.Name = category.Name;
            dbCate.ParentCategory = category.ParentCategory;
            dbCate.ParentCategoryId = category.ParentCategoryId;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var data = await _context.Categories.FindAsync(id);
            if(data == null)
                return NotFound();
            _context.Categories.Remove(data);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

BigonWebShoppingApp/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace BigonWebShoppingApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BigonWebShoppingApp/Areas/Admin/Views/Category/Create.cshtml
@model Category 
<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <!-- Main-body start -->
        <div class="main-body">
            <div class="page-wrapper">
                <!-- Page-header start -->
                <div class="page-header">
                    <div class="row align-items-end">
                        <div class="col-lg-8">
                            <div class="page-header-title">
                                <div class="d-inline">
                                    <h4>Create Category</h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="page-header-breadcrumb">
                                <ul class="breadcrumb-title">
                                    <li class="breadcrumb-item" style="float: left;">
                                        <a href="@Url.Action("Index","Dashboard")"> <i class="feather icon-home"></i> </a>
                                    </li>
                                    <li class="breadcrumb-item" style="float: left;">
                                        <a href="@Url.Action("Index","Category")">Category List</a>
                                    </li>
                                    
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Page-header end -->
                <!-- Page body start -->
                <div class="page-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <!-- Basic Form Inputs card start -->
                            <div class="card">
                                <div class="card-block">
                                    <h4 class="sub-title">Basic Inputs</h4>
                                    <form method="post" asp-action="Create" asp-controller="Category">
                                        <div class="form-group row">
                                            <label asp-for="Name" class="col-sm-2 col-form-label">
                                                Name
                                            </label>
                                            <div class="col-sm-10">
                                                <input asp-for="Name" class="form-control">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label asp-for="Name" class="col-sm-2 col-form-label">
                                                Select Parent Category
                                            </label>
                                            <select asp-for="ParentCategoryId" asp-items="@(new SelectList(ViewBag.Categories,nameof(Model.Id),nameof(Model.Name)))" class="form-control form-control-primary">
                                                <option disabled selected>Categories</option>
                                            </select>
                                        </div>
                                       <button type="submit" class="btn btn-success">Create</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Page body end -->
            </div>
        </div>
        <!-- Main-body end -->
        <div id="styleSelector">
        </div>
    </div>
</div>

BigonWebShoppingApp/Areas/Admin/Views/Category/Edit.cshtml
@model Category
<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <!-- Main-body start -->
        <div class="main-body">
            <div class="page-wrapper">
                <!-- Page-header start -->
                <div class="page-header">
                    <div class="row align-items-end">
                        <div class="col-lg-8">
                            <div class="page-header-title">
                                <div class="d-inline">
                                    <h4>Edit Categoory</h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="page-header-breadcrumb">
                                <ul class="breadcrumb-title">
                                    <li class="breadcrumb-item" style="float: left;">
                                        <a href="@Url.Action("Index","Dashboard")"> <i class="feather icon-home"></i> </a>
                                    </li>
                                    <li class="breadcrumb-item" style="float: left;">
                                        <a href="@Url.Action("Index","Category")">Category List</a>
                                    </li>

                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Page-header end -->
                <!-- Page body start -->
                <div class="page-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <!-- Basic Form Inputs card start -->
                            <div class="card">
                                <div class="card-block">
                                    <h4 class="sub-title">Basic Inputs</h4>
                                    <form method="post" asp-action="Edit" asp-controller="Category">
                                        <div class="form-group row">
                                            <label asp-for="Name" class="col-sm-2 col-form-label">
                                                Name
                                            </label>
                                            <div class="col-sm-10">
                                                <input asp-for="Name" class="form-control">
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label asp-for="Name" class="col-sm-2 col-form-label">
                                                Select Parent Category
                                            </label>
                                            <select asp-for="ParentCategoryId" asp-items="@(new SelectList(ViewBag.Categories,nameof(Model.Id),nameof(Model.Name)))" class="form-control form-control-primary">
                                                <option disabled selected>Categories</option>
                                            </select>
                                        </div>
                                        <button type="submit" class="btn btn-warning">Edit</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Page body end -->
            </div>
        </div>
    </div>
</div>

BigonWebShoppingApp/Areas/Admin/Views/Category/Index.cshtml
@model List<Category>
<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <!-- Main-body start -->
        <div class="main-body">
            <div class="page-wrapper">
                <!-- Page-header start -->
                <div class="page-header">
                    <div class="row align-items-end">
                        <div class="col-lg-8">
                            <div class="page-header-title">
                                <div class="d-inline">
                                    <h4>Category Table</h4>
                                    <a class="btn btn-success" href="@Url.Action("Create","Category")">Create</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="page-header-breadcrumb">
                                <ul class="breadcrumb-title">
                                    <li class="breadcrumb-item" style="float: left;">
                                        <a href="@Url.Action("Index","Dashboard")"> <i class="feather icon-home"></i> </a>
                                    </li>
                                    <li class="breadcrumb-item" style="float: left;">
                                        <a href="@Url.Action("Index","Category")">Basic Table</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Page-header end -->
                <!-- Page-body start -->
                <div class="page-body">

                    <!-- Basic table card start -->
                    <div class="card">
                        <div class="card-header">
                            <h5>Basic Table</h5>
                            <span>use class <code>table</code> inside table element</span>

                        </div>
                        <div class="card-block table-border-style">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Name</th>
                                            <th>Parent Category</th>
                                            <th>Created Date</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @{
                                            foreach (var item in Model)
                                            {
                                                <tr>
                                                    <th scope="row">@item.Id</th>
                                                    <td>@item.Name</td>
                                                    @{
                                                        if (@item.ParentCategory == null)
                                                        {
                                                            <td>Base Category</td>
                                                        }
                                                        else
                                                        {
                                                            <td>@item.ParentCategory.Name</td>
                                                        }
                                                    }
                                                    <td>@item.CreatedDate</td>
                                                    <td>
                                                        <a class="btn btn-warning" asp-route-id="@item.Id" asp-action="Edit" asp-controller="Category">Edit</a>
                                                        <a class="btn btn-danger" asp-route-id="@item.Id" asp-action="Delete" asp-controller="Category">Delete</a>
                                                    </td>
                                                </tr>
                                            }
                                        }

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!-- Basic table card end -->

                </div>
                <!-- Page-body end -->
            </div>
        </div>
        <!-- Main-body end -->

        <div id="styleSelector">
        </div>
    </div>
</div>